### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/app/log/run.log'

### ISSUE THREAD

**Issue by sanju1111** [spacepatcher/Firehol-IP-Aggregator#26]

**Comment by sanju1111** [comment]
ile "/app/sync.py", line 12, in <module>  
FeedsStorage = FeedsStorage()
File "/app/modules/db_sync.py", line 11, in __init__
super().__init__()
File "/app/modules/general.py", line 41, in __init__
format="%(asctime)s [%(levelname)s] [%(filename)s] %(funcName)s: %(message)s")
File "/usr/lib/python3.6/logging/__init__.py", line 1808, in basicConfig
h = FileHandler(filename, mode)
File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
StreamHandler.__init__(self, self._open())
File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/app/log/run.log'

**Comment by spacepatcher** [comment]
Hi @sanju1111!

Looks like the problem is in mismatch of host user's `uid` and user's `uid` in Docker container. This is a common issue with Docker volume permissions, which is well explained here: https://medium.com/@nielssj/docker-volumes-and-file-system-permissions-772c1aee23ca. 

Because of a possible security issue, I prefer not to use default root user in Docker containers. Thus a user without privileged permissions was created in the container, which by default has `uid` 1000. In my environment, I have an OS user with `uid` 1000, and the user in Docker has the same `uid`. That's why the issue is not relevant for me. 

The universal decision is to change permissions recursively for directory `docker-persistent/`:
```
sudo chown -R 1000 docker-persistent/*
```
Also, the problem may be related to SELinux.
